repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix]
        types_or: [python, pyi, jupyter]

      - id: ruff-format
        name: ruff (format)
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
        name: biome (lint)
        additional_dependencies:
          - "@biomejs/biome@2.4.13"
        files: ^frontend/
        exclude: ^frontend/(?:dist|.*/dist)/
        args: ["--config-path=biome.json"]
        types_or: [javascript, jsx, ts, tsx, json, css]

      - id: biome-format
        name: biome (format)
        additional_dependencies:
          - "@biomejs/biome@2.4.13"
        files: ^frontend/
        exclude: ^frontend/(?:dist|.*/dist)/
        args: ["--config-path=biome.json"]
        types_or: [javascript, jsx, ts, tsx, json, css]