services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
  
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
  

  # mcp-server:
  #   build:
  #     context: ./mcp-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "127.0.0.1:9000:9000"
  #   env_file:
  #     - .env
  #   environment:
  #     MCP_SERVER_HOST: "0.0.0.0"
  #     POSTGRES_HOST: "postgres"
  #     QDRANT_HOST: "http://qdrant"
  #     QDRANT_PORT: "6333"
  #   depends_on:
  #     - postgres
  #     - qdrant

  # backend:
  #   build:
  #     context: ./mcp-client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "127.0.0.1:8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     MCP_SERVER_URL: "http://mcp-server:9000"
  #     POSTGRES_HOST: "postgres"
  #     REDIS_HOST: "redis"
  #   depends_on:
  #     - mcp-server
  #     - postgres
  #     - redis

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   environment:
  #     NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
  #     BACKEND_URL_INTERNAL: "http://backend:8000"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
  qdrant_storage:

networks:
  default:
    name: agentics-network
